### ISSUE TITLE
Error connot use import statement outside a module

### ISSUE THREAD

**Issue by fabioginzel** [Jex-y/jwt-on-kms#3]
Details:

    /home/node/app/node_modules/jwt-on-kms/dist/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { GetPublicKeyCommand, SignCommand, SigningAlgorithmSpec, } from '@aws-sdk/client-kms';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

**Comment by Jex-y** [comment]
Should be fixed in v1.2.9 release
